name: Bug Report
description: Something is broken
title: "[bug] "
labels: ["bug", "inbox"]
body:
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Extension version
      placeholder: "0.1.0"
